esphome:
  name: ir-blaster-seminarraum

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "chaosdorf iot"
  password: "PASSWORD"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ir-Blaster-Seminarraum"
    password: "PASSWORD"

captive_portal:
    
# IR configuration entry
remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: "Power LED Strip"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xE31C
        repeat:
          times: 2
          wait_time: 1000ms

    turn_off_action:
      remote_transmitter.transmit_nec:
        address: 0xEF00
        command: 0xE21D
        repeat:
          times: 2
          wait_time: 1000ms

button:
  - platform: template
    name: "Brightness Up"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xE11E

  - platform: template
    name: "Brightness Down"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xE01F

  - platform: template
    name: "Red"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xFF00
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Fire"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xFB04
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Tiger"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xF708
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Merigold"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xF30C
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Yellow"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xEF10
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Green"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xFE01
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Pear"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xFA05
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Sky"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xF609
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Cerulean"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xF20D
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Teal"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xEE11
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Blue"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xFD02
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Cobalt"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xF906
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Boysenberry"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xF50A
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Orchid"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xF10E
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Fuchsia"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xED12
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "White"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xFC03
          repeat:
            times: 2
            wait_time: 1000ms

  - platform: template
    name: "Color Mix"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xF807

  - platform: template
    name: "Fade"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xF40B

  - platform: template
    name: "Jump"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xF00F

  - platform: template
    name: "Async Fade"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xEC13

  - platform: template
    name: "Async Jump"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xE817

  - platform: template
    name: "In Waves"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xEB14

  - platform: template
    name: "Strobe"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xEA15

  - platform: template
    name: "Twinkle"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xE916

  - platform: template
    name: "4 Hour Timer"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xE718

  - platform: template
    name: "6 Hour Timer"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xE619

  - platform: template
    name: "8 Hour Timer"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xE51A

  - platform: template
    name: "Timer Off"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xE41B