esphome:
  name: ir-blaster-acer-beamer

esp8266:
  board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ir-Blaster-Acer-Beamer"
    password: !secret wifi_password

captive_portal:
    
# IR configuration entry
remote_transmitter:
  pin: D2
  carrier_duty_percent: 50%

button:
  - platform: template
    name: "On"
    on_press:
      - remote_transmitter.transmit_nec: # 0x10C8E11E (msb), 78871308 (lsb)
          address: 0x1308
          command: 0x7887
    
  - platform: template
    name: "Off"
    on_press:
      - remote_transmitter.transmit_nec: # 2x 0x10C8E11E (msb), 78871308 (lsb)
          address: 0x1308
          command: 0x7887
          repeat:
            times: 2
            wait_time: 600ms